application: sad-training
version: v01
runtime: python27
api_version: 1
threadsafe: no

libraries:
- name: pycrypto
  version: "2.3"

default_expiration: "5d"

builtins:
- remote_api: on
- deferred: on


inbound_services:
- warmup

skip_files:
- config.rb
- Gemfile
- ^(.*/)?.*\.swp$
- static/bb
- content/css
- ^(.*/)?.*\.sqlite$

handlers:
- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /static
  static_dir: static

- url: .*
  script: main.py

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

